## NOTE THIS CLASS IS AUTOGENERATED BY THE APIDOC GENERATOR
## TO CHANGE: script/apidoc/template/apidoc_controller.rb.erb and regenerate
require 'rest_client'
require 'json'

class ApiController < ApplicationController
  
  def index
  end
  
  def test
  end
  
  
  def sample
  end
  
  def project
  end
  
  def chip_type
  end
  
    
end
